language: julia
os:
  - linux
addons:
  apt:
    packages:
    - tree
julia:
  - 1.0
notifications:
  email: false
script:
  - julia --color=yes --project=. -e 'using Pkg; Pkg.instantiate(); Pkg.build()'
  - julia --color=yes --project=. -e 'using AWSAPI; AWSAPI.generate_all()'
  - 'cd .. && tree || true'
#jobs:
#  include:
#    - stage: "Documentation"
#      julia: 1.0
#      os: linux
#      script:
#        - julia --project=docs/ -e 'using Pkg; Pkg.instantiate()'
#        - julia --project=docs/ docs/make.jl
#      after_success: skip
